services:
  go-integration-email:
    container_name: go-integration-email
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - go-network

networks:
  go-network:
    external: true
    driver: bridge
