services:
  go-integration-email:
    container_name: go-integration-email
    build:
      context: .
      dockerfile: debug/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: go run cmd/app/main.go
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
