services:
  go-integration-email:
    container_name: go-integration-email
    restart: unless-stopped
    build:
      context: .
      dockerfile: debug/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    working_dir: /app
    command: ["go", "run", "./cmd/app/main.go"]
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - go-network

networks:
  go-network:
    external: true
    driver: bridge
